[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { workspace = true }
application = { workspace = true }

argon2 = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
