repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt      # Enforces formatting via rustfmt
      - id: cargo-check # Fast syntax and compilation check
      - id: clippy   # Lints code for common mistakes
